# Generated by Django 5.1.6 on 2025-04-06 18:48

from django.db import migrations

def add_default_tags(apps, schema_editor):
    Tag = apps.get_model('projects', 'Tag')
    default_tags = [
        {'name': 'Technology'},
        {'name': 'Health'},
        {'name': 'Education'}, 
        {'name': 'Art'},
        {'name': 'Other'}
    ]
    for tag_data in default_tags:
        Tag.objects.get_or_create(**tag_data)

class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0003_project_is_active_comment_report_rating'),
    ]

    operations = [
        migrations.RunPython(add_default_tags),
    ]
